/**
 * OpenTime YAML Exporter
 *
 * Serializes OpenTimeDocument to YAML format for .ot files
 */

import { OpenTimeDocument, OpenTimeItem, RepeatsSettings } from './types/opentime';

export class OpenTimeExporter {
    private pluginVersion: string;

    constructor(pluginVersion: string = '1.0.0') {
        this.pluginVersion = pluginVersion;
    }

    /**
     * Export document to YAML string
     */
    export(document: OpenTimeDocument): string {
        const lines: string[] = [];

        // Header
        lines.push(`# OpenTime Export`);
        lines.push(`# Generated by Obsidian OpenTime Export Plugin`);
        lines.push('');

        // Document metadata
        lines.push(`opentime_version: "${document.opentime_version}"`);
        if (document.default_timezone) {
            lines.push(`default_timezone: "${document.default_timezone}"`);
        }
        lines.push(`generated_by: "Obsidian OpenTime Export ${this.pluginVersion}"`);
        lines.push(`created_at: "${new Date().toISOString()}"`);
        lines.push('');

        // Items
        lines.push('items:');
        for (const item of document.items) {
            lines.push(...this.serializeItem(item));
        }

        return lines.join('\n');
    }

    /**
     * Serialize a single item to YAML lines
     */
    private serializeItem(item: OpenTimeItem): string[] {
        const lines: string[] = [];
        const indent = '    ';  // 4 spaces for list item fields

        // Start item
        lines.push(`  - type: ${item.type}`);
        lines.push(`${indent}id: ${this.quote(item.id)}`);
        lines.push(`${indent}title: ${this.quote(item.title)}`);

        // Type-specific fields
        switch (item.type) {
            case 'goal':
                lines.push(`${indent}kind: goal`);
                if (item.target_date) lines.push(`${indent}target_date: ${this.quote(item.target_date)}`);
                if (item.progress !== undefined) lines.push(`${indent}progress: ${item.progress}`);
                if (item.estimate_minutes) lines.push(`${indent}estimate_minutes: ${item.estimate_minutes}`);
                if (item.project_id) lines.push(`${indent}project_id: ${this.quote(item.project_id)}`);
                if (item.repeats) {
                    lines.push(...this.serializeRepeats(item.repeats, indent));
                }
                break;

            case 'task':
                lines.push(`${indent}status: ${item.status}`);
                if (item.due) lines.push(`${indent}due: ${this.quote(item.due)}`);
                if (item.scheduled_start) lines.push(`${indent}scheduled_start: ${this.quote(item.scheduled_start)}`);
                if (item.estimate_minutes) lines.push(`${indent}estimate_minutes: ${item.estimate_minutes}`);
                if (item.actual_minutes) lines.push(`${indent}actual_minutes: ${item.actual_minutes}`);
                if (item.priority !== undefined) lines.push(`${indent}priority: ${item.priority}`);
                if (item.goal_id) lines.push(`${indent}goal_id: ${this.quote(item.goal_id)}`);
                if (item.project_id) lines.push(`${indent}project_id: ${this.quote(item.project_id)}`);
                if (item.repeats) {
                    lines.push(...this.serializeRepeats(item.repeats, indent));
                }
                break;

            case 'habit':
                if (item.pattern) {
                    lines.push(`${indent}pattern:`);
                    if (item.pattern.freq) lines.push(`${indent}  freq: ${item.pattern.freq}`);
                    if (item.pattern.days_of_week) {
                        lines.push(`${indent}  days_of_week: [${item.pattern.days_of_week.join(', ')}]`);
                    }
                }
                if (item.window) {
                    lines.push(`${indent}window:`);
                    if (item.window.start_time) lines.push(`${indent}  start_time: ${this.quote(item.window.start_time)}`);
                    if (item.window.end_time) lines.push(`${indent}  end_time: ${this.quote(item.window.end_time)}`);
                }
                if (item.streak) {
                    lines.push(`${indent}streak:`);
                    if (item.streak.current !== undefined) lines.push(`${indent}  current: ${item.streak.current}`);
                    if (item.streak.longest !== undefined) lines.push(`${indent}  longest: ${item.streak.longest}`);
                }
                if (item.estimate_minutes) lines.push(`${indent}estimate_minutes: ${item.estimate_minutes}`);
                if (item.goal_id) lines.push(`${indent}goal_id: ${this.quote(item.goal_id)}`);
                if (item.project_id) lines.push(`${indent}project_id: ${this.quote(item.project_id)}`);
                if (item.repeats) {
                    lines.push(...this.serializeRepeats(item.repeats, indent));
                }
                break;

            case 'reminder':
                lines.push(`${indent}time: ${this.quote(item.time)}`);
                if (item.repeat) lines.push(`${indent}repeat: ${this.quote(item.repeat)}`);
                if (item.link) lines.push(`${indent}link: ${this.quote(item.link)}`);
                break;

            case 'event':
                lines.push(`${indent}start: ${this.quote(item.start)}`);
                lines.push(`${indent}end: ${this.quote(item.end)}`);
                if (item.all_day !== undefined) lines.push(`${indent}all_day: ${item.all_day}`);
                if (item.timezone) lines.push(`${indent}timezone: ${this.quote(item.timezone)}`);
                if (item.location) lines.push(`${indent}location: ${this.quote(item.location)}`);
                if (item.recurrence) lines.push(`${indent}recurrence: ${this.quote(item.recurrence)}`);
                if (item.goal_id) lines.push(`${indent}goal_id: ${this.quote(item.goal_id)}`);
                if (item.project_id) lines.push(`${indent}project_id: ${this.quote(item.project_id)}`);
                break;

            case 'appointment':
                lines.push(`${indent}start: ${this.quote(item.start)}`);
                lines.push(`${indent}end: ${this.quote(item.end)}`);
                lines.push(`${indent}attendees: [${item.attendees.map(a => this.quote(a)).join(', ')}]`);
                if (item.location) lines.push(`${indent}location: ${this.quote(item.location)}`);
                if (item.provider) lines.push(`${indent}provider: ${this.quote(item.provider)}`);
                if (item.goal_id) lines.push(`${indent}goal_id: ${this.quote(item.goal_id)}`);
                if (item.project_id) lines.push(`${indent}project_id: ${this.quote(item.project_id)}`);
                break;

            case 'project':
                lines.push(`${indent}kind: project`);
                if (item.children && item.children.length > 0) {
                    lines.push(`${indent}children:`);
                    for (const child of item.children) {
                        lines.push(`${indent}  - ${child}`);
                    }
                }
                if (item.progress !== undefined) lines.push(`${indent}progress: ${item.progress}`);
                if (item.target_date) lines.push(`${indent}target_date: ${this.quote(item.target_date)}`);
                if (item.estimate_minutes) lines.push(`${indent}estimate_minutes: ${item.estimate_minutes}`);
                break;
        }

        // Common fields
        if (item.tags && item.tags.length > 0) {
            lines.push(`${indent}tags: [${item.tags.map(t => this.quote(t)).join(', ')}]`);
        }
        if (item.categories && item.categories.length > 0) {
            lines.push(`${indent}categories: [${item.categories.map(c => this.quote(c)).join(', ')}]`);
        }
        if (item.notes) {
            if (item.notes.includes('\n')) {
                lines.push(`${indent}notes: |`);
                for (const line of item.notes.split('\n')) {
                    lines.push(`${indent}  ${line}`);
                }
            } else {
                lines.push(`${indent}notes: ${this.quote(item.notes)}`);
            }
        }
        if (item.steps && item.steps.length > 0) {
            lines.push(`${indent}steps:`);
            for (const step of item.steps) {
                lines.push(`${indent}  - id: ${this.quote(step.id)}`);
                lines.push(`${indent}    title: ${this.quote(step.title)}`);
                lines.push(`${indent}    completed: ${step.completed}`);
                lines.push(`${indent}    order: ${step.order}`);
                lines.push(`${indent}    status: ${step.status}`);
                if (step.due_date) {
                    lines.push(`${indent}    due_date: ${this.quote(step.due_date)}`);
                }
            }
        }
        if (item.links && item.links.length > 0) {
            lines.push(`${indent}links:`);
            for (const link of item.links) {
                lines.push(`${indent}  - kind: ${link.kind}`);
                lines.push(`${indent}    value: ${this.quote(link.value)}`);
            }
        }

        // Obsidian extension
        if (item.x_obsidian) {
            lines.push(`${indent}x_obsidian:`);
            lines.push(`${indent}  source_file: ${this.quote(item.x_obsidian.source_file)}`);
            if (item.x_obsidian.folder_path) {
                lines.push(`${indent}  folder_path: ${this.quote(item.x_obsidian.folder_path)}`);
            }
            if (item.x_obsidian.line_number !== undefined) {
                lines.push(`${indent}  line_number: ${item.x_obsidian.line_number}`);
            }
            if (item.x_obsidian.original_text) {
                lines.push(`${indent}  original_text: ${this.quote(item.x_obsidian.original_text)}`);
            }
        }

        lines.push('');  // Empty line between items
        return lines;
    }

    /**
     * Serialize repeats/recurrence settings to YAML lines
     */
    private serializeRepeats(repeats: RepeatsSettings, indent: string): string[] {
        const lines: string[] = [];
        lines.push(`${indent}repeats:`);
        lines.push(`${indent}  enabled: ${repeats.enabled}`);
        if (repeats.count !== undefined) {
            lines.push(`${indent}  count: ${repeats.count}`);
        }
        if (repeats.per) {
            lines.push(`${indent}  per: ${repeats.per}`);
        }
        if (repeats.weekdays && repeats.weekdays.length > 0) {
            lines.push(`${indent}  weekdays: [${repeats.weekdays.map(d => this.quote(d)).join(', ')}]`);
        }
        if (repeats.end_type) {
            lines.push(`${indent}  end_type: ${repeats.end_type}`);
        }
        if (repeats.end_count !== undefined) {
            lines.push(`${indent}  end_count: ${repeats.end_count}`);
        }
        if (repeats.end_date) {
            lines.push(`${indent}  end_date: ${this.quote(repeats.end_date)}`);
        }
        return lines;
    }

    /**
     * Quote a string for YAML, handling special characters
     */
    private quote(value: string): string {
        // Check if quoting is needed
        const needsQuotes = /[:#[\]{}|>&*?!,'"%@`]|^\s|\s$|^-\s|^$/;
        if (needsQuotes.test(value) || value.includes('\n')) {
            // Escape internal quotes and wrap
            return `"${value.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
        }
        return value;
    }
}
